### ISSUE TITLE
Add "boat mode" UI to Solex

### ISSUE THREAD

**Issue by Pedals2Paddles** [ArduPilot/SoloScripts#6]
Issue
------
Many Solo users are excited about the green cube and ArduCopter 3.5+ because they want to operate off a boat or other moving vehicle.  To do this, the user needs to disable `INS_GYR_CAL`.  It would also be wise to force enable Return to Me if the mobile device has a GPS.  There may be some other odds and ends to toggle as well that I can't think of off the top of my head.

There is currently no user friendly way to do this stuff in any application.  Adding the functionality to Solex would fill the void.  Tagging @kellyschrock.

To Do
-------
* Make a Boat Mode UI in the Solex _Vehicle Settings_ menu.  Enabling boat mode should set those required parameters and application settings.  Likewise disabling Boat Mode should put them back to normal. 
* There should be some kind of indication on the HUD overlay or across the top that the vehicle is in Boat Mode.  I know real estate is getting slim on the screen. But it is important information for the user to know since it affects operations.
* The UI needs to be inhibited if the Solo is not a Pixhawk 2.1 running ArduCopter 3.5+.  I think that `INS_GYR_CAL` parameter is not part of the old stock 3DR firmware so looking for that might be the way to check.

**Comment by proficnc** [comment]
May I suggest that a check for boat mode in Solex? 

So when it's not being used on a boat, that the user is warned?

**Comment by tommy-b-10** [comment]
I'll be adding this to SidePilot as well, just ordered a GC so I will soon be able to contribute more to this!
